### ISSUE TITLE
Support for stop points

### ISSUE THREAD

**Issue by designermonkey** [mkay581/scroll-js#10]
Not really an issue, sorry.

I am looking for a native script that can manage scrolling and stopping at specific points along the page, like screens.

We have each section full height, and the scroll behaviour is required to stop at the edge of each section.

Can this be done with this script?

**Comment by mkay581** [comment]
No worries! Absolutely. You can scroll to any element on the page by passing the element to the `toElement()` method. Let me know if you have any more questions. Glad to help out

**Comment by designermonkey** [comment]
Thanks for the feedback. I will have a go at writing a little wrapper to hijack window scroll and force it to stop at each element.

**Comment by mkay581** [comment]
Okay no problem. If you don't want to use [`toElement()`](https://github.com/mkay581/scroll-js/blob/master/src/scroll.js#L139-L166) in this package, you can always write code to do it manually if you're up for it.
