### ISSUE TITLE
Errors with brunch

### ISSUE THREAD

**Issue by designermonkey** [mkay581/scroll-js#11]
I am using Brunch.io to pack all the code together, and when installing this via `npm`, I get the following error:

```
20 Jul 17:01:47 - error: undefined of node_modules/scroll-js/src/scroll.js failed. rror: 'import' and 'export' may only appear at the top level (6:0)
```

I have no idea what's causing this, and I've never come across this before.

If I can provide any information you need, please ask.

**Comment by mkay581** [comment]
I'm not too familiar with the brunch.io package. What command are you running? looks like brunch is compiling all packages in your project into one file and doesnt like this package uses the `import` statement. This looks to be a brunch.io issue rather than with this package.

**Comment by mkay581** [comment]
After researching this a bit, it looks like you might not have the correct babel options specified in your [brunch configuration](https://github.com/babel/babel-brunch#configuration) file.

**Comment by designermonkey** [comment]
Sadly, I don't use babel, I use `npm`

**Comment by mkay581** [comment]
Not sure i understand. Brunch has a npm plugin that is called [babel-brunch](https://github.com/babel/babel-brunch) that you could use for packages that use the latest ES syntax. It's meant specifically for your purposes. All newer, modern npm packages use latest ES syntax that will require babel. So you're going to run into this issue when using other npm packages--not just this one.

**Comment by mkay581** [comment]
Going to close this for now since this is not an issue with this package. Let me know if you need any additional help.

**Comment by designermonkey** [comment]
Sorry, I didn't get back to you quick enough.

I have babel set up correctly, and it processes all npm packages and all JavaScript code that brunch processes.

The default ignore pattern for babel-brunch doesn't include `node_modules` path, so it's not ignoring files from there.

Sadly, this is the only package so far in months of use on a variety of projects that I have come across this issue :(

I'll have to have a dig around then to see what it is :/
