### ISSUE TITLE
Massive NPM package

### ISSUE THREAD

**Issue by dominikfiala** [mkay581/scroll-js#21]
Just wanna let you know that I tried to use scroll-js via NPM yesterday, but was shocked to wait for 240 secs till about 3 hundred dependencies get installed. Maybe Bower package is not so heavy, but Bower is no being abandoned.
Are all those babel dependencies necessary? All I really need is one JS file. I believe the library works great, at least as I read the description, but the collateral damage of having about 300 deps installed is no for me.

**Comment by mkay581** [comment]
Just to clarify, this package only has [only four dependencies](https://github.com/mkay581/scroll-js/blob/master/package.json#L46-L51) at the time of this writing. These dependencies are necessary to allow the use of ES6 syntax and features while also being backwards compatible (mainly for IE browsers). 

You should note that when using the npm package, it is assuming that you are building your own dist file. And even though other nested deps are installed, they are not shipped with your production code, so it shouldn't make a difference of how many packages get installed.  

If you are only interested in the smallest JS file possible without having to install npm deps, I suggest you download the [dist files](https://github.com/mkay581/scroll-js/tree/master/dist) directly (as indicated in the [Installation instructions on the README](https://github.com/mkay581/scroll-js#installation)).

I am closing this as this is not an issue. However, please feel free to still comment here and I will make time to address any further concerns.

**Comment by dominikfiala** [comment]
Thanks for your reply! It seems that we differ in NPM philosophy.
I never considered to build dist files of third party packages in Node ecosystem. I always thought that building third-party packages is meant only for development of the package. And I thought that thats the reason for devDependencies.

**Comment by mkay581** [comment]
@dominikfiala I understand your concerns. The reason the package was built this way to give developers a way to use their own build processes to ensure the final output would be as small as possible. However, for the reasons you've stated and out of convenience, I do think it is best at this point to point the npm package at the dist file and remove the unnecessary dependencies to customize the build.

I have done this and added it to version 1.8 (latest version) of this package. Thanks for your contribution.
