### ISSUE TITLE
IE11 Support

### ISSUE THREAD

**Issue by rkumorek** [mkay581/scroll-js#42]
Hey,

Does this package supports IE11? I have tried it today but can't make it work on IE11 due to an error. `SCRIPT1006: Expected ')'`
Not sure if it's my webpack setup breaking stuff or it just doesn't work currently on IE.

Thanks

**Comment by mkay581** [comment]
Thanks for filing issue! Yeah it does work in IE11. How are you importing the package? Are you bundling the package with your app? Maybe you can post your code here and what line the error is on here so I can see whats happening?

**Comment by rkumorek** [comment]
Hey,

Thanks for quick reply. I've created simple repo using random webpack starter.

**Comment by mkay581** [comment]
@rkumorek Thanks for your repro, that really helped me understand what the problem was. This is fixed in #43. Do you mind pulling that down and making sure it fixes your issue? Thanks!
