### ISSUE TITLE
No manual scroll available while the script running.

### ISSUE THREAD

**Issue by oneakroller** [mkay581/scroll-js#9]
The user can not use the browser internal scroll function while the script running in chrome 50.0.2661.102 m.

**Comment by oneakroller** [comment]
Script running I mean while the script scroll the page.

**Comment by mkay581** [comment]
> The user can not use the browser internal scroll function

Just to clarify, what do you mean by "can not"? Is there an error you see? And what is the expected behavior? Thanks for reporting 👍

**Comment by mkay581** [comment]
Closing due to no response. @oneakroller, feel free to comment here again with details if you're still having problems.
